server:
  port: 8101
spring:
  application:
    name: mall-monitor
  security: # 配置登录用户名和密码
    user:
      name: macro
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.200.128:8848
      config:
        server-addr: http://192.168.200.128:8848
        file-extension: yaml